name: Build and Deploy
on:
  push:
    branches:
      - testing-cd
    paths:
      - client/**
      - .github/workflows/front.yml
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        working-directory: ./client

      - name: Install and Build front in github actionsğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        working-directory: ./client
        run: |
          npm install
          npm run build
        env:
          REACT_APP_URL_API: http://192.168.0.50:3001/
          REACT_APP_URL_BASE: /FT10-PI-Countries
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        working-directory: ./client
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
       